### ISSUE TITLE
Image URL is relative

### ISSUE THREAD

**Issue by zlobec** [abwebdevelopers/oc-imageresize-plugin#10]
Hi,

I have a test website, that's installed on a subfolder. The plugin creates a relative URL link and the links don't load images from the cache (the domain and subfolder is missing).

I can make a workaround adding the |app filter on the image url, but I don't think it's a general solution. The plugin should generate an absolute link.

Regard,
Darjan

PS: i'm running the installation on a non-SSL server...

**Comment by bradietilley** [comment]
Issue is fixed in v2.1.3

If you continue to have issues, let me know and we can go over it in detail.
