### ISSUE TITLE
Bad TTFB when using this module

### ISSUE THREAD

**Issue by PubliAlex** [abwebdevelopers/oc-imageresize-plugin#15]
Hello,

I have very bad TTFB as soon as I resize images using this module.

I created 2 sample files just containing 35 images each.

One with the following code :

    <img src="{{ 'dummy.png'|media }}" />
    <img src="{{ 'dummy.png'|media }}" />
    etc.... (35 times)

The other with the following code :

    <img src="{{ 'dummy.png'|media|resize(1000) }}" />
    <img src="{{ 'dummy.png'|media|resize(1000) }}" />
    etc.... (35 times)

When I compare TTFB, the first page is 182ms, the second page : 934ms.

The difference in TTFB seems quite heavy, and does not decrease even if reload the page several times. I could understand a high TTFB on the first page load, when all images needs to be resized, but don't understand for the next page load, when cached images should be served.

What do you think about this ?

Best regards,

Alex

**Comment by bennothommo** [comment]
@PubliAlex can you confirm if it is loading the cached image on the second load, or if it is trying to resize the image again?

**Comment by PubliAlex** [comment]
Cached images seems to be served as the following condition is triggered for each images in the resize() function : 

        if ($cached = $this->getCache()) {
            trace_log('cached'); // It's triggered for each images in the page that use the |resize filter
            return $cached;
        }

I'm surprized to see that the server take about 1 full second to get about 30 cached path. But it doesn't seems to be an image cache problem.

Do you have the same performance impact difference than me if you try to create the 2 same test pages ?

Best regards,

Alex

**Comment by bennothommo** [comment]
@PubliAlex We've used this plugin on a fair few websites now, some with several images on a page, and can't say that we have encountered a huge slowdown, but we'll definitely take a look.

@bradietilley have you spotted any performance issues with this plugin?

**Comment by bradietilley** [comment]
@bennothommo No performance issues from what I can tell, but that being said I am interested to see if we can optimise this plugin. I'll take a look when I get a chance.

**Comment by bennothommo** [comment]
@bradietilley I'd recommend, if it's possible, deferring any images that are yet to be resized by giving an intermediary URL that will render the resized image once loaded, as opposed to trying to resize it right there and then. That way, the yet-to-be-resized images do not block the loading of the page.

**Comment by Zmove** [comment]
@bennothommo Thank you for the advice, I'm not familiar with this technic, but will investigate.

**Comment by PubliAlex** [comment]
Wow, the base idea seems wonderful, a kind of lazyloading, but server side ? And you already made a PR ? I'm ready to test it as soon as possible if you need some feedbacks !

**Comment by PubliAlex** [comment]
I tested the new master branch and my TTFB heavily dropped (900ms to 380ms after the update for the same page), congratulation !

**Comment by bennothommo** [comment]
@PubliAlex that's great to hear! Thanks for reporting it to us.
