### ISSUE TITLE
Add watermark to images

### ISSUE THREAD

**Issue by PubliAlex** [abwebdevelopers/oc-imageresize-plugin#17]
Hello,

I believe intervention image allow to add watermark to images. Would it be possible to add this feature to this module ?

Thank you

Alex

**Comment by bradietilley** [comment]
We can definitely add this functionality. Would you like to open a PR for this and start implementing this feature?

**Comment by PubliAlex** [comment]
PR added #19 

Here is an example for the implementation : 

`<img src="{{ 'dummy.png'|media|resize(500, null, { 'insert': 'storage/app/media/logo.png,bottom-left,30,30' }) }}" alt="" />`

Parameters are in the string, separated by a comma `,` in that order : 
- $path of the watermark image (mandatory)
- $position (optional)
- $x offset (optional)
- $y offset (optional)

As I suck in regex, and not sure about the right syntax for the different parameters, I left it empty.

One possible improvement could be to add some settings to globally apply a watermark to all images on a website, not sure if it could be useful or a per image method is enought.

Best regards,

Alex
