### ISSUE TITLE
Cache folder location

### ISSUE THREAD

**Issue by PubliAlex** [abwebdevelopers/oc-imageresize-plugin#18]
Hello,

Not sure if it's due to a recent change, but I noticed an "imageresizecache" folder in the media manager.

I'm not sure storing cache here is a good idea, it should be in a /storage/temp instead don't you think ?

Best regards,

Alex

**Comment by Zmove** [comment]
Agree : once website is developped and given to final customer, they always have a question about that "strange folder" on their media space.

**Comment by bradietilley** [comment]
Please upgrade to v2.1.1 which moves the default imageresizecache directory to another publicly accessible directory: `storage/temp/public/imageresizecache` which should be a seamless upgrade for all

**Comment by PubliAlex** [comment]
@bradietilley Nice to hear, another cool addition would be to provide a dashboard widget to clear file cache now it's not in media anymore as we can't ask to final user to make a ssh commande in order to clean folder cache.

**Comment by bradietilley** [comment]
@PubliAlex Sounds like that would be very beneficial. I'll see if I have time this week to implement that.

**Comment by bradietilley** [comment]
@PubliAlex Please see v2.1.4 for a new dashboard widget (+ bugfix)

**Comment by PubliAlex** [comment]
@bradietilley Wow already ? Are you human ? :)

**Comment by bradietilley** [comment]
@PubliAlex No, Elon Musk is my creator :stuck_out_tongue:

**Comment by PubliAlex** [comment]
Negative, I'm a meat popsicle was also a good answer :)

![image](https://user-images.githubusercontent.com/55833027/82309223-29f7ce80-99c3-11ea-8c2c-ead8c52d7a44.png)
