### ISSUE TITLE
Cached image MIME is image/jpeg ?

### ISSUE THREAD

**Issue by zlobec** [abwebdevelopers/oc-imageresize-plugin#22]
I'm getting some strange behavior from the cached resized images.

Firstly, there is no file extension. I can't tell if this is by design or because of a bug? Can somebody explain if there could be a downside to not having file extensions?

Secondly, the MIME from cached image is always image/jpeg... ?
For example: when the image first resizes and loads from:
`/imageresize/9a0c7...`
everything is OK... image MIME is set as in the resize format, but then when the image loads from:
`/storage/app/media/imageresizecache//5e6/697/bb4/5e669...`
the response MIME shows always as "image/jpeg".

So making images webp format they still get loaded from cache as jpeg. The file sizes are pretty much the same, but all the speedtest tools give lower score for using jpeg file format.

Is this just me? I've been trying to optimize a webpage for the whole day today and I seem to be already a bit muddy from all the code...

Thanks,
Darjan

**Comment by bennothommo** [comment]
@zlobec Thanks for the report, we will take a look.

**Comment by bradietilley** [comment]
See v2.1.1

The temporary (lazy resize) URL now contains the extension, but I don't know if it changes anything.    Also cached images are now stored with the extension as well, so serving them should yield the correct mime type.

Anyway, have a look and if the issue persists then let me know.
