### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by otrebor-3** [abwebdevelopers/oc-imageresize-plugin#25]
The problem I am currently facing is that the plugin creates an image with no extention and when the browser  recalls it, it is always displayed image not found.

**Comment by mediaclinic** [comment]
Kind a same problem, but I think I have a problem with path: image is not found as it does not generate full path to cached file.

**Comment by mediaclinic** [comment]
I think, it has something to do with install folder. I have installed it on subfolder, and then the cache is not working. Same problem/solution as here? 

https://github.com/toughdeveloper/oc-imageresizer-plugin/commit/dc6486d1d5f841806b5f814807adc96fd868fa82

**Comment by otrebor-3** [comment]
In my case it looks like the path is correct and  correctly recalled. It seems that it is the image without extension that can't be displayed either  recalling it from the browser with tag <img src="..."> or displaying it from finder as shown in the attached file.

![image_extension](https://user-images.githubusercontent.com/65295867/82157522-43453180-9882-11ea-8f9b-72aa08bc8a05.png)

**Comment by bradietilley** [comment]
I'll take a look sometime this week and get a fix out for it. Does anyone have any recommendations for where this plugin should store the cached images?

- `storage/imageresizecache` (eh)
- `storage/cache/imageresize` (maybe)
- `storage/framework/cache/imageresize` (don't know about mixing a plugin's cache with the framework storage)

Keep in mind the directory needs to be publicly accessible

**Comment by bennothommo** [comment]
My vote is for option two or three - there's no harm mixing it up with the framework's cache, it would even allow `artisan cache:clear` to reset the cached images too.

**Comment by bradietilley** [comment]
I went with `storage/temp/public/imageresize/` as this is one of the few directories that's naturally exposed to the public (see .htaccess) which is fundamental for this plugin, I think. The other directories are blacklisted so using them would require us to edit the `.htaccess` file to allow accessing the directory, but we ain't WordPress so we're not touching that file :sweat_smile:

Probably best it's not in framework anyway as I imagine _some_ users would prefer that `cache:clear` does _not_ wipe the resized images, especially those sites that have thousands of images that takes a long time to "warm"

See v2.1.1. Any issues, let me know.

**Comment by mediaclinic** [comment]
I noticed on subfolder installation (both on local environment with MAMP and on webserver) URL for the image is not working. Image can not be found. But, if the installation is on main folder/domain, works perfectly.

**Comment by bradietilley** [comment]
@mediaclinic Interesting.... could I please get you to play around with this plugin on your installation to test a fix for it?

I'm wondering if I should wrap any URL that this plugin generates in `url()` in order to get the correct absolute path. If I understand your issue correctly, `url()` might fix it :thinking: 

~~edit: going to test myself and probably just release an update for it, as it seems people want absolute URLs~~ Done

**Comment by bradietilley** [comment]
@mediaclinic Can you please update to v2.1.3? I have wrapped the URLs in `url()` which now generates absolute URLs for all resized images (first-time and cached). I think this should fix the issue you're encountering but let me know if it doesn't and we can go over the issue in detail.

**Comment by mediaclinic** [comment]
@bradietilley Works perfectly on all cases! Just a guess, but trasnfering site to a new folder/domain, one has to remember clearing the image cache then.

**Comment by bradietilley** [comment]
@mediaclinic Definitely, yeah. Although when transferring a site one should probably should clear ALL cache as best practice.

I could maybe add a setting to do what Ben mentioned above, to assist in clearing cache, so those who want the `cache:clear` to remove the resized cached images can have it their way, and those who don't want images to be wiped every deployment can opt against it. Might do that later this week

**Comment by bradietilley** [comment]
@mediaclinic  @bennothommo 

Ended up just doing it now - there's a new setting as of v2.1.5 that, when enabled, runs `imageresize:clear` after `cache:clear` is run, meaning you can clear images and cache all in one command. By default this option is disabled but may enable it by default in the next major release... don't know.
