### ISSUE TITLE
Issue on MySQL upgrade

### ISSUE THREAD

**Issue by mediaclinic** [abwebdevelopers/oc-imageresize-plugin#33]
Got error, when tried to upgrade:

"SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB/TEXT column 'options' can't have a default value (SQL: create table `abweb_imageresize_permalinks` (`id` int unsigned not null auto_increment primary key, `identifier` text not null, `image` text not null, `mime_type` varchar(191) not null, `extension` varchar(191) not null, `options` text not null default '{}', `path` text null, `resized_at` datetime null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB)" on line 664 of /var/www/.../vendor/laravel/framework/src/Illuminate/Database/Connection.php"

Worked fine before.

**Comment by bradietilley** [comment]
@mediaclinic can you please try again with version 2.2.2?

**Comment by mediaclinic** [comment]
Works like a charm!
