### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by PubliAlex** [abwebdevelopers/oc-imageresize-plugin#37]
Hello,

When I try to uninstall this module from backend, I get an error : 

> "Call to undefined method Illuminate\Database\Schema\SQLiteBuilder::dropTable()" on line 261 of /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php

October version : 470

Best regards

**Comment by bennothommo** [comment]
@PubliAlex please change the following line in the `plugins/abwebdevelopers/imageresize/updates/create_permalinks_table.php` (line 32):

```php
Schema::dropTable('abweb_imageresize_permalinks');
```

to

```php
Schema::drop('abweb_imageresize_permalinks');
```

and then you should be able to uninstall. I'll push a fix out for this now.
