### ISSUE TITLE
Webp format is not supported by PHP installation

### ISSUE THREAD

**Issue by ghost** [abwebdevelopers/oc-imageresize-plugin#4]
Hello,

When I try to convert a .png to a .webp, I get the following error message : 

> An exception has been thrown during the rendering of a template ("Webp format is not supported by PHP installation.").

I get the same error using GD or ImageMagick. Some lines about webp support would be great in the doc.

Congratulation for this great plugin.

**Comment by bradietilley** [comment]
Thanks for the feedback, I'll be sure to document that next release

**Comment by bradietilley** [comment]
Added a note for `webp` in the readme.
