### ISSUE TITLE
Space in filename = Image not found

### ISSUE THREAD

**Issue by ghost** [abwebdevelopers/oc-imageresize-plugin#8]
Hello,

If there is space in filename and you try to do something like that : 

`<img src="{{ 'my picture.jpg'|media|resize(800) }}" alt="" />`

It display the not found image.

If you remove `|resize(800)` it works, if you change the filename for `my_picture.jpg` it works.

**Comment by bradietilley** [comment]
Hey, try update the plugin to 1.1.5 - let me know if you still have issues.
