### ISSUE TITLE
After 1.1.5 update plugin not working

### ISSUE THREAD

**Issue by zlobec** [abwebdevelopers/oc-imageresize-plugin#9]
Hi,

after the update to 1.1.5. errors appear: class/Resizer.php at row 637 - regarding the return type void not being correct. I had to quickly revert back to 1.1.4, because I installed on a production page, so i don't have the exact error message.

**Comment by PubliAlex** [comment]
Same here, quite critical issue.

**Comment by bradietilley** [comment]
Hi guys, fixed (1.1.6) - sorry about that.

I really need to figure out a proper way to introduce unit tests to CI :thinking:

**Comment by zlobec** [comment]
@bradietilley Tried 1.1.6 on a test site and it seemd to work. Gonna try a production page soon, will report if it's ok.
